package com.ssf.membership.model;

public enum RMNCHAServiceStatus {
    NEW, BC_ONGOING, PC_ONGOING,
    EC_REGISTERED, ANC_REGISTERED, ANC_ONGOING, PNC_OUTCOME_REGISTERED,
    PNC_INFANT_REGISTERED, PNC_ONGOING, CHILDCARE_REGISTERED, CHILDCARE_ONGOING,
    ADOLESCENTCARE_REGISTERED, ADOLESCENTCARESERVICE_ONGOING
}
