import React, { useState, useEffect } from "react";
import { Col, Row, Modal, Button } from "react-bootstrap";
import SaveButton from "../../EMR_Buttons/SaveButton";
import StockReportTable from "./StockReportTable";

export default function StockModal(props) {
  let tableData = props.tableData;
  let type = props.type;

  function printDiv() {
    let page = $("#printDiv").DataTable();
    // var printContents = document.getElementById(divName).innerHTML;
    // var originalContents = document.body.innerHTML;

    // document.body.innerHTML = printContents;

    window.print(page);

    // document.body.innerHTML = originalContents;
  }

  return (
    <React.Fragment>
      <Modal
        show={props.printStocKModal}
        onHide={props.printStockClose}
        className="print-stock-div-modal"
      >
        <div id="printDiv">
          <div className="phc-name-div">
            <h5 className="vital-header">
              {" "}
              Sugganahalli Rural PHC{" "}
              <i
                className="fa fa-close close-btn-style"
                onClick={props.printStockClose}
              ></i>
            </h5>
          </div>
          <div className="stock-status-div">
            <Row className="stock-info-div">
              <Col lg={4} md={4}>
                <p className="info-stock-para">
                  Stock Status as On :<b> 28th Jan 2023 </b>
                </p>
                <p className="info-stock-para">
                  Report Type :&nbsp;
                  <b>
                    {props.type == "consolidated" && "Consolidated"}
                    {props.type == "detailed" && "Detailed"}
                  </b>
                </p>
                <p className="info-stock-para">Classification :-</p>
              </Col>
              <Col lg={4} md={4}></Col>
              <Col lg={4} md={4}>
                <p className="info-stock-para">
                  Report Generated by :
                  <b> Mr. Ravikrishna Reddy, Pharmacist </b>
                </p>
                <p className="info-stock-para">
                  Report Generated Time :<b> 12:53 P.M. </b>
                </p>
              </Col>
            </Row>
            <div className="modal-table-stock">
              <h3 className="dia-heading selected-stock-date text-center">
                {props.type == "consolidated" && "Consolidated"}
                {props.type == "detailed" && "Detailed"}
                &nbsp;Stock Report
              </h3>
              <StockReportTable tableData={tableData} type={type} />
            </div>
            <div className="regFoot align-me2 resetButton">
              <div className="save-btn-section">
                <SaveButton
                  butttonClick={props.printStockClose}
                  class_name="regBtnPC"
                  button_name="Cancel"
                />
              </div>
              <div className="save-btn-section">
                <Button variant="primary" className="regBtnN">
                  <i className="bi bi-printer"></i>&nbsp; Print
                </Button>
              </div>
            </div>
          </div>
        </div>
      </Modal>
    </React.Fragment>
  );
}
