package com.ssf.surveycube.constant;

public enum SurveyType {
    VILLAGE, HOUSEHOLD, INDIVIDUAL,
    AVAILABILITYOFPUBLICFACILITIESINTHEVILLAGE,
    INFRASTRUCTUREINTHEVILLAGE, QUALITYOFENVIRONMENTANDSANITATIONINTHEVILLAGE,
    WATERSOURCESINTHEVILLAGE, DIABETESEXAMINATION, DIABETESTEST, DIABETESHISTORYSYMPTOMS,EMRPATEINT
}
