package com.ssf.homevisit.requestmanager;

import com.ssf.homevisit.BuildConfig;

public interface AppDefines {
    String clientID = "661utgb6numlsl33u58dc7092j";
    String BASE_URL = BuildConfig.BASE_URL;
    String COGNITO_URL = BuildConfig.COGNITO_URL;
    String COGNITO_CLIENT_ID = BuildConfig.COGNITO_CLIENT_ID;
    String X_AMZ_TARGET_VALUE = BuildConfig.X_AMZ_TARGET_VALUE;
    String CRASH_ANALYTICS_APP_KEY = BuildConfig.CRASH_ANALYTICS_APP_KEY;

    String PREFERENCES = "appPreferences";
    String X_AMZ_TARGET = "X-Amz-Target";
    String APICONTENTTYPE = "Content-Type";
    String APICONTENTTYPEVALUECOGNITO = "application/x-amz-json-1.1";

    String TOKEN_TYPE = "token_type";
    String USER_NAME = "username";
    String USER_ID ="userId";
    String HOUSEHOLD_ID="householdId";
    String IS_LOGIN = "is_login";
    String ACCESS_TOKEN = "access_token";
    String TOKEN_EXPIRE = "token_expire";
    String ID_TOKEN = "id_token";
    String REFRESH_TOKEN = "refresh_token";
    String VILLAGE_LEVEL_MAPPING = "village_level_mapping";
    String VILLAGE_LEVEL_SURVEILLANCE_MAPPING = "village_level_surveillance_mapping";
    String HOUSE_LEVEL_MAPPING = "house_level_mapping";
    String VILLAGE_LEVEL_SOCIO_ECONOMIC_SURVEY = "village_level_socio_economic_survey";
    String FROM_LOGIN = "login";
    String MAIN = "main";
    String VILLAGE_NAME="VILLAGE_NAME";
    String VILLAGE_LGD_CODE="VILLAGE_LGD_CODE";
    String VILLAGE_UUID="VILLAGE_UUID";
    String HOUSEHOLD_SE_SURVEY = "household_se_survey";
    String INDIVIDUAL_SE_SURVEY = "individual_se_survey";
    String HNW_VILLAGE_SURVEILLANCE = "hnw_village";
    String HNW_HOUSEHOLD_SURVEILLANCE = "hnw_household";
    String HNW_INDIVIDUAL_SURVEILLANCE = "hnw_individual";
    String FLOW_TYPE = "flow_type";
    String ASSET_TYPE = "asset_type";
    String LARVA_ACTION = "Perform Larva Surveillance";
    String IODINE_ACTION = "Perform Iodine Surveillance";
    String ELIGIBLE_COUPLE_REGISTRATION = "ELIGIBLE_COUPLE_REGISTRATION";
    String ENVIRONMENT_SANITATION = "QualityOfEnvironmentAndSanitationInTheVillage";
    String TRANSPORT_MODE= "AvailableModeOfTransportInTheVillage";
    String WATER_SOURCE="WaterSourcesInTheVillage";
    String PUBLIC_FACILITY="AvailabilityOfPublicFacilitiesInTheVillage";
    String PHYSICAL_INFRA="InfrastructureInTheVillage";
    String RETURN_FLOW="Return_Flow";
    String OPTION_NAME="OPTION_NAME";
    String PULSE_POLIO = "pulse_polio";
    String VHSNC = "vhsnc";
    String ARS = "ars";
    String WATER_SAMPLE_TEST = "WATER_SAMPLE_TEST";
    String IODINE_TEST = "IODINE_TEST";
    String LARVA_TEST = "LARVA_TEST";
    String PLACE_DETAILS = "Place_Details";
    String HOUSEHOLD_DETAILS = "Household_details";
    String IDSP_S_Form = "IDSP S-Form";
    String BLOOD_SMEAR = "BLOOD SMEAR";
    String ACTIVE_CASE_FINDING = "ACTIVE CASE FINDING";
    String URINE_SAMPLE = "URINE SAMPLE";
    String LEPROSY = "LEPROSY";
    String LEPROSY_LAB_RESULT_END_URL = "/leprosysurveillance-svc/leprosySurveillances/status/filter";
    String BLOOD_SMEAR_LAB_RESULT_END_URL = "/bssurveillance-svc/bloodsmearsurveillances/status/filter";
    String ACF_LAB_RESULT_END_URL = "/tbsurveillance-svc/tbsurveillance/status/filter";
    String URINE_LAB_RESULT_END_URL = "/urinesurveillance-svc/urinesamplesurveillances/status/filter";
    String COVID = "COVID";
    String SURVEILLANCE_TYPE = "SURVEILLANCE_TYPE";
    String INDIVIDUAL_SELECTION = "INDIVIDUAL_SELECTION";
    String HOUSE_UUID = "HOUSE_UUID";
    String CITIZEN_UUID = "CITIZEN_UUID";
    String CITIZEN_INFO = "CITIZEN_INFO";
    String HealthAndWellness_IndividualLevel_Leprosy = "HealthAndWellness_IndividualLevel_Leprosy";
    String HealthAndWellness_IndividualLevel_UrineSample = "HealthAndWellness_IndividualLevel_UrineSample";
    String HealthAndWellness_IndividualLevel_IDSP = "HealthAndWellness_IndividualLevel_IDSP";
    String HealthAndWellness_IndividualLevel_Covid = "HealthAndWellness_IndividualLevel_Covid";
    String HealthAndWellness_IndividualLevel_ActiveCaseFinding = "HealthAndWellness_IndividualLevel_ActiveCaseFinding";
    String HealthAndWellness_IndividualLevel_BloodSmear = "/HealthAndWellness_IndividualLevel_BloodSmear";
    String HealthAndWellness_IndividualLevel_BloodSmear_Filaria = "HealthAndWellness_IndividualLevel_BloodSmear_Filaria";
    String HealthAndWellness_IndividualLevel_BloodSmear_Malaria = "HealthAndWellness_IndividualLevel_BloodSmear_Malaria";
    String IndividualLevel_BloodSmear_Filaria = "IndividualLevel_BloodSmear_Filaria";
    String IndividualLevel_BloodSmear_Malaria = "IndividualLevel_BloodSmear_Malaria";
    String PENDING_STATUS="PENDING_STATUS";
    String TEST_RESULT_DATA="TEST_RESULT_DATA";
    String EC_REGISTRATION_UTILITY_URL="/formutility/RMNCH+A_EC_Registration";
    String EC_SERVICE_UTILITY_URL="/formutility/RMNCH+A_EC_Services";
    String ANC_REGISTRATION_UTILITY_URL="/formutility/RMNCH+A_ANC_Registration";
    String ANC_SERVICE_UTILITY_URL="/formutility/RMNCH+A_ANC_Services";
    String PNC_DELIVERY_OUTCOME_UTILITY_URL="/formutility/RMNCH+A_PNC_DeliveryOutcomeDetails";

    String PNC_INFANT_UTILITY_URL ="/formutility/RMNCH+A_PNC_InfantDetails";

    String WATER_SAMPLE_ID="WATER_SAMPLE_ID";
    String CHILD_ID = "CHILD_ID";
    String CHILD_MOTHER_DETAILS = "CHILD_MOTHER_DETAILS";
}