name: BaseProgram.CI.DEV
on:
  push:
     branches: main
  pull_request:
     branches: main

# Env variables for DEV environment
env:
  profile: ${{ secrets.PROFILE }}
  secret: ${{ secrets.SECRET }}
  accesskey: ${{ secrets.ACCESSKEY }}
  secretkey: ${{ secrets.SECRETKEY }}
  region: ${{ secrets.REGION }}
  IMAGE_NAME: sampoornaswarajfoundation/baseprogram

jobs:
  build:
    name: ⚒️ Build App
    runs-on: ubuntu-latest    
    steps:
    
    - name: Checkout Main Repo
      uses: actions/checkout@v2
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml --batch-mode --update-snapshots verify
    
    - name: Run Junit Tests
      run: mvn -B test --file pom.xml
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: test/test-results.xml

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: artifact
        path: ${{github.workspace}}/target
  
  gcr-push:
    name: 🐳 Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: artifact
        path: ${{github.workspace}}/target
    
    - name: Checkout Docker Repo
      uses: actions/checkout@v2
      with:
        repository: SampoornaSwarajFoundation/PHC_Infrastructure
        ref: main
        path: baseprogram
        token: ${{ secrets.GHPAT}}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: v0.7.0
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.GCR }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHPAT }}
    
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
    
    - name: Build and Push Image
      id: gcr_push
      uses: docker/build-push-action@v2
      with:
          context: .
          file: baseprogram/baseprogram/Dockerfile
          push: true
          tags: |
            ghcr.io/sampoornaswarajfoundation/baseprogram:latest
            ghcr.io/sampoornaswarajfoundation/baseprogram:${{ steps.date.outputs.date }}.${{ github.run_number }}

  deploy:
    name: 📦 Deploy to DEV
    environment:
      name: DEV
    needs: [build, gcr-push]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v2
        with:
          repository: SampoornaSwarajFoundation/PHC_Infrastructure
          ref: main
          path: dev
          token: ${{ secrets.GHPAT}} 
      
      - name: Change directory to dev
        run: |
              cd dev/dev/
              ls -ltr
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.7
          cli_config_credentials_token: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        id: init
        run: |
            cd dev/dev/
            terraform init
        working-directory: ${{ github.workspace }}
      
      - name: Terraform Validate
        id: validate
        run: |
            cd dev/dev/
            terraform validate -no-color
      
      - name: Terraform Plan
        id: plan
        run: |
            cd dev/dev/
            terraform plan -no-color
        working-directory: ${{ github.workspace }}
      
      - name: Get Image Version
        id: image-version
        env: 
          SECRETS_CONTEXT: "${{ toJson(secrets) }}"
        run: |
          $secrets = ($env:SECRETS_CONTEXT | ConvertFrom-Json -AsHashtable)
          $token = $secrets.GHPAT
          $object = Invoke-RestMethod -Method Get -Uri https://api.github.com/orgs/SampoornaSwarajFoundation/packages/container/baseprogram/versions -Headers @{Authorization = 'Bearer ' + $token}
          $tags = $object.metadata.container.tags
          $imageversion = $tags[0]
          Write-Output $imageversion
          echo "::set-output name=imageversion::$imageversion" 
        shell: pwsh 
      
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
            cd dev/dev/
            terraform apply -auto-approve -var='baseprogram-svc-image=ghcr.io/sampoornaswarajfoundation/baseprogram:${{steps.image-version.outputs.imageversion}}'
        working-directory: '${{ github.workspace }}'
