package com.ssf.homevisit.fragment.vhnd

object VHNDTopics {
    const val ELIGIBLE_COUPLE_Q1 = "Provide the total no. of Eligible Couple in the meeting"
    const val ELIGIBLE_COUPLE_Q2 = "No. of Counselling on Family planning done"
    const val ELIGIBLE_COUPLE_Q3 = "No. of ECs who received OCP"
    const val ELIGIBLE_COUPLE_Q4 = "No. of ECs who received CC"
    const val ELIGIBLE_COUPLE_Q5 = "No. of IUCD - Counselling done"

    const val ANC_Q1 = "Provide the total no. of ANC women in the meeting"
    const val ANC_Q2 = "No. of tetanus toxoid injections(TT) given"
    const val ANC_Q3 = "No. of blood pressure measurement done"
    const val ANC_Q4 = "No. of blood test done"
    const val ANC_Q5 = "No. of abdominal examinations done"
    const val ANC_Q6 = "No. of counselling on diet and rest done"
    const val ANC_Q7 = "No. of IFA tablets given"
    const val ANC_Q8 = "No. of calcium tablets given"
    const val ANC_Q9 = "No. of women counselled for institutional delivery"
    const val ANC_Q10 = "No. of women referred up due to danger signs"

    const val PNC_Q1 = "Provide the total no. of PNC women in the meeting"
    const val PNC_Q2 = "Provide the total no. of PNC infants in the meeting"
    const val PNC_Q3 = "No. of IFA tablets given to PNC women"
    const val PNC_Q4 = "No. of calcium tablets given to PNC women"
    const val PNC_Q5 = "No. of women counselled for breast feeding"
    const val PNC_Q6 = "No. of children to whom ORS is given (0 to 5 years)"
    const val PNC_Q7 = "No. of women referred up due to danger signs"
    const val PNC_Q8 = "No. of infants referred up due to danger signs"

    const val CHILD_CARE_Q1 = "Provide the total no. of children in the meeting"
    const val CHILD_CARE_Q2 = "No. of Vaccinations Provided(Below 1 Year)"
    const val CHILD_CARE_Q3 = "No. of Vaccinations Provided(1-2 Year)"
    const val CHILD_CARE_Q4 = "No. of Vaccinations Provided(2-3 Year)"
    const val CHILD_CARE_Q5 = "No. of Vaccinations Provided(3-4 Year)"
    const val CHILD_CARE_Q6 = "No. of Vaccinations Provided(4-5 Year)"
    const val CHILD_CARE_Q7 = "No. of Vaccinations Provided(5-6 Year)"
    const val CHILD_CARE_Q8 = "No. of referral up for children below 2 Years"
    const val CHILD_CARE_Q9 = "No. of medications for children below 2 Years"
    const val CHILD_CARE_Q10 = "No. of children to whom ORS is given (0 to 5 years)"

    const val ADS_CARE_Q1 = "Provide the total no. of adolescents in the meeting(Male)"
    const val ADS_CARE_Q2 = "Provide the total no. of adolescents in the meeting(Female)"
    const val ADS_CARE_Q3 = "No. of Counselling done on other topics done"
    const val ADS_CARE_Q4 = "No. of IFA tablets given(Male)"
    const val ADS_CARE_Q5 = "No. of IFA tablets given(Female)"
    const val ADS_CARE_Q6 = "No. of calcium tablets given(Male)"
    const val ADS_CARE_Q7 = "No. of calcium tablets given(Female)"
    const val ADS_CARE_Q8 = "No. of Counselling on Family planning (Early marriage)"
    const val ADS_CARE_Q9 = "No. of OCP provided (Early marriage)"
    const val ADS_CARE_Q10 = "No. of CC provided (Early marriage)"
}